networks:
  default:
    external:
      name: roboshop

services:
  mongodb:
    image: mongodb:v1

  catalogue:
    image: catalogue:v1
    depends_on:
      - mongodb

  redis:
    image: redis

  cart:
    image: cart:v1
    depends_on:
      - redis
      - catalogue

  user:
    image: user:v1
    depends_on:
      - redis
      - mongodb

  web:
    image: web:v1
    ports:
    - "80:80"
    depends_on:
      - catalogue
      - mongodb
      - cart
      - user
