networks:
  default:
    external:
      name: roboshop


## docker run -d --name <container_name> --network+<default_network> <image_name>:<version>
## docker run -d --name mongodb --network=roboshop mongodb:1

services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb

  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb

  redis:
    image: redis
    container_name: redis

  cart:
    image: cart:v1
    container_name: cart
    depends_on:
      - redis
      - catalogue

  user:
    image: user:v1
    container_name: user
    depends_on:
      - redis
      - mongodb
  
  mysql:
    image: mysql:v1
    container_name: mysql

  shipping:
   image: shipping:v1
   container_name: shipping
   depends_on:
   - mysql

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=roboshop
      - RABBITMQ_DEFAULT_PASS=roboshop123

  payment:
    image: payment:v1
    container_name: payment
    depends_on:
    - rabbitmq
    
  web:
    image: web:v1
    container_name: web
    ports:
    - "80:80"
    depends_on:
      - catalogue
      - mongodb
      - cart
      - user
      - rabbitmq
      - payment
      - shipping
